version: '3.8'

services:
  node-app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:${PORT}
    environment:
      PORT :  3000
      DATABASE_URL: "mysql://root:mypassword@localhost:3307/mydatabase"
      JWT_SECRET: 98sydf9a7s9dfb6a9sd6f0as8d6f8asd67f0asd76f
    networks:
      - astro-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    ports:
      - "3307:3306" # Map container port 3306 to host port 3307
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount initialization script
    networks:
      - astro-network



networks:
  astro-network:
    driver: bridge
