version: "3.3"

services:
  node-app:
    env_file:
      - .env
    restart: always
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:${PORT}
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - astro-network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    ports:
      - "3306:${MYSQL_PORT}" # Map container port 3306 to host port 3307
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount initialization script
    networks:
      - astro-network

networks:
  astro-network:
    driver: bridge
